const e = require("express");

module.exports = [
    {
        title: "Witcher 3 - Behind The Scenes",
        imageUrl: "https://i.ibb.co/Nx2rQTx/witcher-3.jpg",
        thumbnailUrl: "https://i.ibb.co/fkZmg5m/witcher-3-tumbnail.jpg",
        description: "<p>Ut nisi arcu, vehicula quis facilisis quis, venenatis et justo. Praesent pretium erat ex. Curabitur sed tortor sagittis, ornare purus eget, commodo massa. Proin porta odio odio, ut sodales lectus mattis eget. Sed molestie, diam nec vehicula facilisis, eros metus tempus erat, sodales semper ex turpis vitae velit. In id quam vitae velit pretium blandit scelerisque ac mi.</p><p>Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Proin porttitor, elit eget vehicula porttitor, massa nunc iaculis dolor, nec eleifend metus enim sit amet arcu. Donec vel augue erat. Ut leo nulla, viverra eget ligula ut, tempor rhoncus felis. Proin porttitor turpis metus, et convallis nulla maximus quis.</p><h1>Venenatis augue ornare</h1><p>Donec dictum dolor nec nisl condimentum, id fringilla felis dictum. Curabitur a laoreet quam. Sed hendrerit neque eu dolor faucibus lacinia. Quisque in nulla at enim bibendum tempor. Maecenas elementum sollicitudin turpis, eu malesuada magna varius sed.</p><h1>Praesent vehicula efficitur nulla et sagittis</h1><p>Nunc eget imperdiet purus. Fusce posuere porttitor nisi nec aliquam. Praesent suscipit lacus nisl, in ultricies justo hendrerit sollicitudin. Suspendisse potenti. Donec a nisi non ex efficitur scelerisque eget id nulla. Quisque laoreet augue metus, ut sodales turpis tempus sit amet.</p><p>Donec condimentum justo non venenatis fermentum. Mauris a nulla quam. Fusce posuere velit turpis, congue accumsan odio vulputate nec. Vestibulum aliquam ligula at erat tincidunt viverra. Vivamus id tellus venenatis, pulvinar augue in, convallis diam.</p><p>Morbi vulputate eros sapien, vel dignissim diam tempor ac. Vestibulum vitae tortor congue, fermentum dolor vel, venenatis libero.</p>",
        category: "Production",
        viewCount: 3502,
        commentCount: 25
    },
    {
        title: "New Dark Souls Game Announced",
        imageUrl: "https://i.ibb.co/5vpDSwf/dark-souls.jpg",
        thumbnailUrl: "https://i.ibb.co/4tSg8YQ/dark-souls-thumbnail.jpg",
        description: "<p>Nullam id tempus ipsum. Nam sed mauris nisl. Morbi vel scelerisque risus, ut bibendum orci. Nunc sit amet massa ac lectus varius commodo quis vitae est. Ut sollicitudin consequat nisl scelerisque consequat. Nullam vel nulla a elit fringilla ullamcorper nec eu mi. Nulla pulvinar nulla eu tempor malesuada. Praesent varius dapibus luctus.</p><h1>consectetur velit non consequat facilisis</h1><p>Ut dolor velit, dictum ac fermentum fringilla, aliquet semper sapien. Aliquam varius dictum cursus. Sed eu consequat orci, sed scelerisque ex. Sed pellentesque consequat dui vitae vestibulum. Nullam bibendum sed purus vitae malesuada.</p><p>Fusce feugiat cursus iaculis. Cras ac pretium lectus. Aenean condimentum, mi eu imperdiet faucibus, nunc justo bibendum dolor, ut condimentum mauris ex eu magna. Proin pellentesque ut metus ut bibendum. Phasellus consectetur dictum eleifend.</p><p>Duis feugiat ante eu arcu scelerisque, sed sodales augue congue. Mauris vehicula turpis nec sem viverra pulvinar. Nullam eleifend, mauris a ultricies varius, arcu felis tincidunt dui, a varius erat purus vel justo.</p><p></p><h1>Nunc nec augue non</h1><p>Ut sit amet finibus quam. Donec et tellus lacus. Pellentesque eget dictum erat. Nunc neque dui, luctus vel volutpat ac, scelerisque vel lacus. Aliquam vel turpis hendrerit, porttitor lacus non, vestibulum turpis. Morbi pretium lacinia hendrerit. In et tellus lacus. Pellentesque rhoncus at justo ac auctor. Vestibulum lacinia erat sodales elementum maximus. Donec et tempus sem.<p><h1>Maecenas in tellus</h1><p>Curabitur feugiat ullamcorper quam, eu porttitor magna laoreet at. Cras nibh urna, porta ut ex sed, ultricies euismod nunc. Donec ultrices a leo in convallis. Maecenas vitae nunc a neque blandit venenatis eu id tellus. Nulla efficitur nisi sit amet laoreet venenatis.</p><p>Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras bibendum a elit ut eleifend. Nulla in turpis lacinia, sodales nibh in, feugiat est. Quisque vitae quam urna.</p>",
        category: "News",
        viewCount: 2263,
        commentCount: 33
    },
    {
        title: "Last Of Us 2 Guide",
        imageUrl: "https://i.ibb.co/0Jtyvrf/last-of-us-2.jpg",
        thumbnailUrl: "https://i.ibb.co/J56zXg6/last-of-us-2-thumbnail.jpg",
        description: "<p>Duis posuere augue libero, a pellentesque tortor ultricies a. Phasellus et aliquet nunc, eget suscipit nisi. Integer placerat metus non tortor consectetur aliquet. Aliquam efficitur, tortor eu maximus facilisis, tellus lacus pharetra elit, quis elementum risus mi ut turpis</p><h1>Nulla a nisl justo</h1><p>Nunc euismod et neque in aliquam. Maecenas imperdiet vel mi non tincidunt. Morbi turpis sapien, vehicula porttitor lacus nec, elementum sollicitudin velit. Suspendisse sagittis sagittis magna, ac facilisis lectus pellentesque sit amet.</p><h1>Curabitur sed pulvinar massa</h1><p>Pellentesque dictum lectus lacus, sed ultricies eros pharetra non. Pellentesque gravida quam eu dolor consequat ultrices. Sed gravida ultricies risus, ac sagittis mauris ullamcorper id. Morbi facilisis sapien eget turpis auctor, ut posuere mauris aliquam. Vivamus auctor nec neque vitae vulputate.</p><h1>Sed nec pharetra</h1><p>Fusce vehicula consectetur lectus, non hendrerit mi egestas in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus non felis sodales, tristique lacus eget, vulputate sem.</p><p>Maecenas dolor magna, tempor sed dictum quis, consequat sit amet justo. Mauris sed cursus nunc. Donec hendrerit, turpis eget eleifend aliquam, leo risus euismod lorem, vel aliquam libero urna vitae odio. Aliquam blandit tortor at euismod scelerisque.</p>",
        category: "Guide",
        viewCount: 1820,
        commentCount: 12
    },
    {
        title: "Tomb Raider Gameplay Trailer",
        imageUrl: "https://i.ibb.co/YNMtDZD/tomb-raider.jpg",
        thumbnailUrl: "https://i.ibb.co/VWnk24z/tomb-raider-thumbnail.jpg",
        description: "<p>Quisque purus arcu, vehicula eget ligula vel, scelerisque faucibus quam. Curabitur sapien quam, rhoncus a finibus volutpat, tristique sit amet libero. Aliquam felis mauris, ultricies vel bibendum ac, hendrerit ac massa. Donec elit est, molestie vitae ipsum ac, condimentum aliquam odio. Sed non suscipit nibh, et pretium lacus. Nunc risus est, scelerisque vitae suscipit id, rhoncus et dui.</p><p>Nulla consequat posuere massa, sit amet porta libero pharetra non. Donec augue sem, maximus non arcu vel, pulvinar sollicitudin neque. Sed rutrum sit amet tortor vitae euismod.</p><h1>Porttitor sagittis sapien</h1><p>Vestibulum consectetur lectus id eros blandit mollis. Donec facilisis ante euismod est fringilla, ac maximus ipsum accumsan. Maecenas finibus lorem a velit congue, iaculis commodo magna scelerisque. Curabitur imperdiet dictum enim.</p><p>Donec ac lacus lectus. Nulla vitae lectus condimentum, posuere quam eu, bibendum nisi. Duis venenatis in eros nec fermentum. Aliquam erat volutpat.</p><h1>Morbi fringilla ornare</h1><p>Aliquam eleifend ante at tortor gravida dignissim. In ac pharetra erat, a dapibus metus. Aliquam laoreet tempus erat ut tincidunt.</p><p>Curabitur fermentum pellentesque velit, non volutpat velit molestie laoreet. Proin eleifend molestie metus a tempus. Vestibulum eget tempus ante. Ut bibendum at libero sed suscipit. Quisque justo tortor, pharetra non lorem non, consectetur ultrices libero. Duis accumsan faucibus eros sit amet euismod.</p>",
        category: "Trailer",
        viewCount: 954,
        commentCount: 5
    },
]